
FROM python:3.11-slim

WORKDIR /app

COPY requirements-etl.txt .

RUN pip install --no-cache-dir -r requirements-etl.txt

COPY . /app

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]