DROP TABLE IF EXISTS currency_metadata;

CREATE TABLE IF NOT EXISTS currency_metadata (
    currency_code TEXT PRIMARY KEY,
    country       TEXT,
    continent     TEXT
);

INSERT INTO currency_metadata (currency_code, country, continent)
VALUES

 ('AED','United Arab Emirates','Asia'),
 ('AFN','Afghanistan','Asia'),
 ('ALL','Albania','Europe'),
 ('AMD','Armenia','Asia'),
 ('ANG','Curaçao and Sint Maarten','North America'),
 ('AOA','Angola','Africa'),
 ('ARS','Argentina','South America'),
 ('AUD','Australia','Oceania'),
 ('AWG','Aruba','North America'),
 ('AZN','Azerbaijan','Asia'),
 ('BAM','Bosnia and Herzegovina','Europe'),
 ('BBD','Barbados','North America'),
 ('BDT','Bangladesh','Asia'),
 ('BGN','Bulgaria','Europe'),
 ('BHD','Bahrain','Asia'),
 ('BIF','Burundi','Africa'),
 ('BMD','Bermuda','North America'),
 ('BND','Brunei','Asia'),
 ('BOB','Bolivia','South America'),
 ('BRL','Brazil','South America'),
 ('BSD','Bahamas','North America'),
 ('BTN','Bhutan','Asia'),
 ('BWP','Botswana','Africa'),
 ('BYN','Belarus','Europe'),
 ('BZD','Belize','North America'),
 ('CAD','Canada','North America'),
 ('CDF','Democratic Republic of the Congo','Africa'),
 ('CHF','Switzerland','Europe'),
 ('CLF','Chile (Unidad de Fomento)','South America'),
 ('CLP','Chile','South America'),
 ('CNH','China (Offshore)','Asia'),
 ('CNY','China','Asia'),
 ('COP','Colombia','South America'),
 ('CRC','Costa Rica','North America'),
 ('CUP','Cuba','North America'),
 ('CVE','Cape Verde','Africa'),
 ('CZK','Czech Republic','Europe'),
 ('DJF','Djibouti','Africa'),
 ('DKK','Denmark','Europe'),
 ('DOP','Dominican Republic','North America'),
 ('DZD','Algeria','Africa'),
 ('EGP','Egypt','Africa'),
 ('ERN','Eritrea','Africa'),
 ('ETB','Ethiopia','Africa'),
 ('EUR','Eurozone','Europe'),
 ('FJD','Fiji','Oceania'),
 ('FKP','Falkland Islands','South America'),
 ('FOK','Faroe Islands','Europe'),
 ('GBP','United Kingdom','Europe'),
 ('GEL','Georgia','Asia'),
 ('GGP','Guernsey','Europe'),
 ('GHS','Ghana','Africa'),
 ('GIP','Gibraltar','Europe'),
 ('GMD','Gambia','Africa'),
 ('GNF','Guinea','Africa'),
 ('GTQ','Guatemala','North America'),
 ('GYD','Guyana','South America'),
 ('HKD','Hong Kong','Asia'),
 ('HNL','Honduras','North America'),
 ('HRK','Croatia','Europe'),
 ('HTG','Haiti','North America'),
 ('HUF','Hungary','Europe'),
 ('IDR','Indonesia','Asia'),
 ('ILS','Israel','Asia'),
 ('IMP','Isle of Man','Europe'),
 ('INR','India','Asia'),
 ('IQD','Iraq','Asia'),
 ('IRR','Iran','Asia'),
 ('ISK','Iceland','Europe'),
 ('JEP','Jersey','Europe'),
 ('JMD','Jamaica','North America'),
 ('JOD','Jordan','Asia'),
 ('JPY','Japan','Asia'),
 ('KES','Kenya','Africa'),
 ('KGS','Kyrgyzstan','Asia'),
 ('KHR','Cambodia','Asia'),
 ('KID','Kiribati','Oceania'),
 ('KMF','Comoros','Africa'),
 ('KRW','South Korea','Asia'),
 ('KWD','Kuwait','Asia'),
 ('KYD','Cayman Islands','North America'),
 ('KZT','Kazakhstan','Asia'),
 ('LAK','Laos','Asia'),
 ('LBP','Lebanon','Asia'),
 ('LKR','Sri Lanka','Asia'),
 ('LRD','Liberia','Africa'),
 ('LSL','Lesotho','Africa'),
 ('LYD','Libya','Africa'),
 ('MAD','Morocco','Africa'),
 ('MDL','Moldova','Europe'),
 ('MGA','Madagascar','Africa'),
 ('MKD','North Macedonia','Europe'),
 ('MMK','Myanmar','Asia'),
 ('MNT','Mongolia','Asia'),
 ('MOP','Macau','Asia'),
 ('MRU','Mauritania','Africa'),
 ('MUR','Mauritius','Africa'),
 ('MVR','Maldives','Asia'),
 ('MWK','Malawi','Africa'),
 ('MXN','Mexico','North America'),
 ('MYR','Malaysia','Asia'),
 ('MZN','Mozambique','Africa'),
 ('NAD','Namibia','Africa'),
 ('NGN','Nigeria','Africa'),
 ('NIO','Nicaragua','North America'),
 ('NOK','Norway','Europe'),
 ('NPR','Nepal','Asia'),
 ('NZD','New Zealand','Oceania'),
 ('OMR','Oman','Asia'),
 ('PAB','Panama','North America'),
 ('PEN','Peru','South America'),
 ('PGK','Papua New Guinea','Oceania'),
 ('PHP','Philippines','Asia'),
 ('PKR','Pakistan','Asia'),
 ('PLN','Poland','Europe'),
 ('PYG','Paraguay','South America'),
 ('QAR','Qatar','Asia'),
 ('RON','Romania','Europe'),
 ('RSD','Serbia','Europe'),
 ('RUB','Russia','Europe'),
 ('RWF','Rwanda','Africa'),
 ('SAR','Saudi Arabia','Asia'),
 ('SBD','Solomon Islands','Oceania'),
 ('SCR','Seychelles','Africa'),
 ('SDG','Sudan','Africa'),
 ('SEK','Sweden','Europe'),
 ('SGD','Singapore','Asia'),
 ('SHP','Saint Helena','Africa'),
 ('SLE','Sierra Leone (New Leone)','Africa'),
 ('SLL','Sierra Leone (Old Leone)','Africa'),
 ('SOS','Somalia','Africa'),
 ('SRD','Suriname','South America'),
 ('SSP','South Sudan','Africa'),
 ('STN','São Tomé and Príncipe','Africa'),
 ('SYP','Syria','Asia'),
 ('SZL','Eswatini','Africa'),
 ('THB','Thailand','Asia'),
 ('TJS','Tajikistan','Asia'),
 ('TMT','Turkmenistan','Asia'),
 ('TND','Tunisia','Africa'),
 ('TOP','Tonga','Oceania'),
 ('TRY','Turkey','Asia'),
 ('TTD','Trinidad and Tobago','North America'),
 ('TVD','Tuvalu','Oceania'),
 ('TWD','Taiwan','Asia'),
 ('TZS','Tanzania','Africa'),
 ('UAH','Ukraine','Europe'),
 ('UGX','Uganda','Africa'),
 ('USD','United States','North America'),
 ('UYU','Uruguay','South America'),
 ('UZS','Uzbekistan','Asia'),
 ('VES','Venezuela','South America'),
 ('VND','Vietnam','Asia'),
 ('VUV','Vanuatu','Oceania'),
 ('WST','Samoa','Oceania'),
 ('XAF','CEMAC (Central Africa)','Africa'),
 ('XCD','Eastern Caribbean States','North America'),
 ('XCG','Crypto Gold Index','N/A'),
 ('XDR','IMF Special Drawing Rights','N/A'),
 ('XOF','UEMOA (West Africa)','Africa'),
 ('XPF','French Pacific Territories','Oceania'),
 ('YER','Yemen','Asia'),
 ('ZAR','South Africa','Africa'),
 ('ZMW','Zambia','Africa'),
 ('ZWG','Zimbabwe (New)','Africa'),
 ('ZWL','Zimbabwe (Old)','Africa')

ON CONFLICT(currency_code) DO NOTHING;
